version: 3
endpoint: https://fitconnect.hasura.app/v1/graphql
metadata_directory: metadata
migrations_directory: migrations
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:4000