sonar.projectKey=gondorwebmaster_fitconnect
sonar.organization=gondorwebmaster

# Rutas de código
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,src/migrations/**,.github/workflows/_docs.yml

# Configuración de TypeScript/JS
sonar.typescript.tsconfigPath=tsconfig.json

# Activar el análisis de tipos
sonar.typescript.typeCheck=true

# Calidad

sonar.cpd.exclusions=**/*.test.ts
# REPORTE DE LINT (ESLint)
sonar.eslint.reportPaths=reports/lint-report/eslint-report.json

# REPORTE DE COBERTURA (Tests)
sonar.javascript.lcov.reportPaths=reports/coverage-artifact/lcov.info
sonar.coverage.exclusions=src/migrations/**