import { Migration } from '@mikro-orm/migrations';

export class Migration20260720181308 extends Migration {

  override async up(): Promise<void> {
    this.addSql(`alter table "article" alter column "title" type varchar(255) using ("title"::varchar(255));`);
    this.addSql(`alter table "article" alter column "title" set not null;`);
    this.addSql(`alter table "article" alter column "published_at" type varchar(255) using ("published_at"::varchar(255));`);
    this.addSql(`alter table "article" alter column "published_at" set not null;`);
    this.addSql(`alter table "article" alter column "description" type varchar(255) using ("description"::varchar(255));`);
    this.addSql(`alter table "article" alter column "description" set not null;`);
    this.addSql(`alter table "article" alter column "link" type varchar(255) using ("link"::varchar(255));`);
    this.addSql(`alter table "article" alter column "link" set not null;`);
    this.addSql(`alter table "article" alter column "image" type varchar(255) using ("image"::varchar(255));`);
    this.addSql(`alter table "article" alter column "image" set not null;`);

    this.addSql(`alter table "company_config" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "company_config" alter column "created_at" set not null;`);
    this.addSql(`alter table "company_config" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "company_config" alter column "updated_at" set not null;`);
    this.addSql(`alter table "company_config" alter column "polls_enabled" type boolean using ("polls_enabled"::boolean);`);
    this.addSql(`alter table "company_config" alter column "polls_enabled" set not null;`);
    this.addSql(`alter table "company_config" alter column "products_enabled" type boolean using ("products_enabled"::boolean);`);
    this.addSql(`alter table "company_config" alter column "products_enabled" set not null;`);
    this.addSql(`alter table "company_config" alter column "chat_enabled" type boolean using ("chat_enabled"::boolean);`);
    this.addSql(`alter table "company_config" alter column "chat_enabled" set not null;`);
    this.addSql(`alter table "company_config" alter column "training_enabled" type boolean using ("training_enabled"::boolean);`);
    this.addSql(`alter table "company_config" alter column "training_enabled" set not null;`);
    this.addSql(`alter table "company_config" alter column "auto_accept_users" type boolean using ("auto_accept_users"::boolean);`);
    this.addSql(`alter table "company_config" alter column "auto_accept_users" set not null;`);

    this.addSql(`alter table "permission" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "permission" alter column "created_at" set not null;`);
    this.addSql(`alter table "permission" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "permission" alter column "updated_at" set not null;`);
    this.addSql(`alter table "permission" alter column "name" type varchar(100) using ("name"::varchar(100));`);
    this.addSql(`alter table "permission" alter column "name" set not null;`);
    this.addSql(`alter table "permission" alter column "module" type text using ("module"::text);`);
    this.addSql(`alter table "permission" alter column "module" set not null;`);
    this.addSql(`alter table "permission" alter column "action" type text using ("action"::text);`);
    this.addSql(`alter table "permission" alter column "action" set not null;`);
    this.addSql(`alter table "permission" alter column "is_active" type boolean using ("is_active"::boolean);`);
    this.addSql(`alter table "permission" alter column "is_active" set not null;`);

    this.addSql(`alter table "schedule_options" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "schedule_options" alter column "created_at" set not null;`);
    this.addSql(`alter table "schedule_options" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "schedule_options" alter column "updated_at" set not null;`);
    this.addSql(`alter table "schedule_options" alter column "max_active_reservations" type int using ("max_active_reservations"::int);`);
    this.addSql(`alter table "schedule_options" alter column "max_active_reservations" set not null;`);
    this.addSql(`alter table "schedule_options" alter column "max_advance_booking_days" type int using ("max_advance_booking_days"::int);`);
    this.addSql(`alter table "schedule_options" alter column "max_advance_booking_days" set not null;`);
    this.addSql(`alter table "schedule_options" alter column "same_day_booking_allowed" type boolean using ("same_day_booking_allowed"::boolean);`);
    this.addSql(`alter table "schedule_options" alter column "same_day_booking_allowed" set not null;`);
    this.addSql(`alter table "schedule_options" alter column "full_open_hours" type int using ("full_open_hours"::int);`);
    this.addSql(`alter table "schedule_options" alter column "full_open_hours" set not null;`);
    this.addSql(`alter table "schedule_options" alter column "booking_cutoff_minutes" type int using ("booking_cutoff_minutes"::int);`);
    this.addSql(`alter table "schedule_options" alter column "booking_cutoff_minutes" set not null;`);
    this.addSql(`alter table "schedule_options" alter column "min_bookings_required" type int using ("min_bookings_required"::int);`);
    this.addSql(`alter table "schedule_options" alter column "min_bookings_required" set not null;`);
    this.addSql(`alter table "schedule_options" alter column "quota_warning_thresholds" type jsonb using ("quota_warning_thresholds"::jsonb);`);
    this.addSql(`alter table "schedule_options" alter column "quota_warning_thresholds" set not null;`);

    this.addSql(`alter table "company" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "company" alter column "created_at" set not null;`);
    this.addSql(`alter table "company" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "company" alter column "updated_at" set not null;`);
    this.addSql(`alter table "company" alter column "name" type varchar(100) using ("name"::varchar(100));`);
    this.addSql(`alter table "company" alter column "name" set not null;`);
    this.addSql(`alter table "company" alter column "phone_number" type varchar(255) using ("phone_number"::varchar(255));`);
    this.addSql(`alter table "company" alter column "phone_number" set not null;`);
    this.addSql(`alter table "company" alter column "email" type varchar(255) using ("email"::varchar(255));`);
    this.addSql(`alter table "company" alter column "email" set not null;`);
    this.addSql(`alter table "company" alter column "address" type varchar(255) using ("address"::varchar(255));`);
    this.addSql(`alter table "company" alter column "address" set not null;`);
    this.addSql(`alter table "company" alter column "is_validated" type boolean using ("is_validated"::boolean);`);
    this.addSql(`alter table "company" alter column "is_validated" set not null;`);
    this.addSql(`alter table "company" alter column "code" type varchar(255) using ("code"::varchar(255));`);
    this.addSql(`alter table "company" alter column "code" set not null;`);

    this.addSql(`alter table "promotion" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "promotion" alter column "created_at" set not null;`);
    this.addSql(`alter table "promotion" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "promotion" alter column "updated_at" set not null;`);
    this.addSql(`alter table "promotion" alter column "title" type varchar(255) using ("title"::varchar(255));`);
    this.addSql(`alter table "promotion" alter column "title" set not null;`);
    this.addSql(`alter table "promotion" alter column "description" type varchar(255) using ("description"::varchar(255));`);
    this.addSql(`alter table "promotion" alter column "description" set not null;`);

    this.addSql(`alter table "product" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "product" alter column "created_at" set not null;`);
    this.addSql(`alter table "product" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "product" alter column "updated_at" set not null;`);
    this.addSql(`alter table "product" alter column "name" type varchar(255) using ("name"::varchar(255));`);
    this.addSql(`alter table "product" alter column "name" set not null;`);
    this.addSql(`alter table "product" alter column "description" type varchar(255) using ("description"::varchar(255));`);
    this.addSql(`alter table "product" alter column "description" set not null;`);
    this.addSql(`alter table "product" alter column "price" type real using ("price"::real);`);
    this.addSql(`alter table "product" alter column "price" set not null;`);
    this.addSql(`alter table "product" alter column "company_id" drop default;`);
    this.addSql(`alter table "product" alter column "company_id" type uuid using ("company_id"::text::uuid);`);
    this.addSql(`alter table "product" alter column "company_id" set not null;`);

    this.addSql(`alter table "plan" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "plan" alter column "created_at" set not null;`);
    this.addSql(`alter table "plan" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "plan" alter column "updated_at" set not null;`);
    this.addSql(`alter table "plan" alter column "name" type varchar(100) using ("name"::varchar(100));`);
    this.addSql(`alter table "plan" alter column "name" set not null;`);
    this.addSql(`alter table "plan" alter column "amount" type bigint using ("amount"::bigint);`);
    this.addSql(`alter table "plan" alter column "amount" set not null;`);
    this.addSql(`alter table "plan" alter column "currency" type varchar(10) using ("currency"::varchar(10));`);
    this.addSql(`alter table "plan" alter column "currency" set not null;`);
    this.addSql(`alter table "plan" alter column "interval" type text using ("interval"::text);`);
    this.addSql(`alter table "plan" alter column "interval" set not null;`);
    this.addSql(`alter table "plan" alter column "interval_count" type smallint using ("interval_count"::smallint);`);
    this.addSql(`alter table "plan" alter column "interval_count" set not null;`);
    this.addSql(`alter table "plan" alter column "status" type text using ("status"::text);`);
    this.addSql(`alter table "plan" alter column "status" set not null;`);
    this.addSql(`alter table "plan" alter column "is_active" type boolean using ("is_active"::boolean);`);
    this.addSql(`alter table "plan" alter column "is_active" set not null;`);

    this.addSql(`alter table "plan_permission" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "plan_permission" alter column "created_at" set not null;`);
    this.addSql(`alter table "plan_permission" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "plan_permission" alter column "updated_at" set not null;`);
    this.addSql(`alter table "plan_permission" alter column "plan_id" drop default;`);
    this.addSql(`alter table "plan_permission" alter column "plan_id" type uuid using ("plan_id"::text::uuid);`);
    this.addSql(`alter table "plan_permission" alter column "plan_id" set not null;`);
    this.addSql(`alter table "plan_permission" alter column "permission_id" drop default;`);
    this.addSql(`alter table "plan_permission" alter column "permission_id" type uuid using ("permission_id"::text::uuid);`);
    this.addSql(`alter table "plan_permission" alter column "permission_id" set not null;`);
    this.addSql(`alter table "plan_permission" alter column "is_active" type boolean using ("is_active"::boolean);`);
    this.addSql(`alter table "plan_permission" alter column "is_active" set not null;`);

    this.addSql(`alter table "picture_url" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "picture_url" alter column "created_at" set not null;`);
    this.addSql(`alter table "picture_url" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "picture_url" alter column "updated_at" set not null;`);
    this.addSql(`alter table "picture_url" alter column "name" type varchar(255) using ("name"::varchar(255));`);
    this.addSql(`alter table "picture_url" alter column "name" set not null;`);
    this.addSql(`alter table "picture_url" alter column "url" type text using ("url"::text);`);
    this.addSql(`alter table "picture_url" alter column "url" set not null;`);

    this.addSql(`alter table "user" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "user" alter column "created_at" set not null;`);
    this.addSql(`alter table "user" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "user" alter column "updated_at" set not null;`);
    this.addSql(`alter table "user" alter column "email" type varchar(255) using ("email"::varchar(255));`);
    this.addSql(`alter table "user" alter column "email" set not null;`);
    this.addSql(`alter table "user" alter column "nickname" type varchar(255) using ("nickname"::varchar(255));`);
    this.addSql(`alter table "user" alter column "nickname" set not null;`);
    this.addSql(`alter table "user" alter column "is_active" type boolean using ("is_active"::boolean);`);
    this.addSql(`alter table "user" alter column "is_active" set not null;`);
    this.addSql(`alter table "user" alter column "is_blocked" type boolean using ("is_blocked"::boolean);`);
    this.addSql(`alter table "user" alter column "is_blocked" set not null;`);
    this.addSql(`alter table "user" alter column "is_verified" type boolean using ("is_verified"::boolean);`);
    this.addSql(`alter table "user" alter column "is_verified" set not null;`);
    this.addSql(`alter table "user" alter column "is_admin_verified" type boolean using ("is_admin_verified"::boolean);`);
    this.addSql(`alter table "user" alter column "is_admin_verified" set not null;`);
    this.addSql(`alter table "user" alter column "is_super_admin" type boolean using ("is_super_admin"::boolean);`);
    this.addSql(`alter table "user" alter column "is_super_admin" set not null;`);

    this.addSql(`alter table "training_task" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "training_task" alter column "created_at" set not null;`);
    this.addSql(`alter table "training_task" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "training_task" alter column "updated_at" set not null;`);
    this.addSql(`alter table "training_task" alter column "content" type varchar(255) using ("content"::varchar(255));`);
    this.addSql(`alter table "training_task" alter column "content" set not null;`);
    this.addSql(`alter table "training_task" alter column "repeat" type boolean using ("repeat"::boolean);`);
    this.addSql(`alter table "training_task" alter column "repeat" set not null;`);
    this.addSql(`alter table "training_task" alter column "company_id" drop default;`);
    this.addSql(`alter table "training_task" alter column "company_id" type uuid using ("company_id"::text::uuid);`);
    this.addSql(`alter table "training_task" alter column "company_id" set not null;`);

    this.addSql(`alter table "schedule_programmed" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "schedule_programmed" alter column "created_at" set not null;`);
    this.addSql(`alter table "schedule_programmed" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "schedule_programmed" alter column "updated_at" set not null;`);
    this.addSql(`alter table "schedule_programmed" alter column "days_of_week" type integer[] using ("days_of_week"::integer[]);`);
    this.addSql(`alter table "schedule_programmed" alter column "days_of_week" set not null;`);
    this.addSql(`alter table "schedule_programmed" alter column "start_hour" type time(0) using ("start_hour"::time(0));`);
    this.addSql(`alter table "schedule_programmed" alter column "start_hour" set not null;`);
    this.addSql(`alter table "schedule_programmed" alter column "end_hour" type time(0) using ("end_hour"::time(0));`);
    this.addSql(`alter table "schedule_programmed" alter column "end_hour" set not null;`);
    this.addSql(`alter table "schedule_programmed" alter column "max_users" type int using ("max_users"::int);`);
    this.addSql(`alter table "schedule_programmed" alter column "max_users" set not null;`);
    this.addSql(`alter table "schedule_programmed" alter column "title" type varchar(255) using ("title"::varchar(255));`);
    this.addSql(`alter table "schedule_programmed" alter column "title" set not null;`);
    this.addSql(`alter table "schedule_programmed" alter column "description" type varchar(255) using ("description"::varchar(255));`);
    this.addSql(`alter table "schedule_programmed" alter column "description" set not null;`);
    this.addSql(`alter table "schedule_programmed" alter column "type" type varchar(255) using ("type"::varchar(255));`);
    this.addSql(`alter table "schedule_programmed" alter column "type" set not null;`);
    this.addSql(`alter table "schedule_programmed" alter column "company_id" drop default;`);
    this.addSql(`alter table "schedule_programmed" alter column "company_id" type uuid using ("company_id"::text::uuid);`);
    this.addSql(`alter table "schedule_programmed" alter column "company_id" set not null;`);

    this.addSql(`alter table "schedule" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "schedule" alter column "created_at" set not null;`);
    this.addSql(`alter table "schedule" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "schedule" alter column "updated_at" set not null;`);
    this.addSql(`alter table "schedule" alter column "title" type varchar(255) using ("title"::varchar(255));`);
    this.addSql(`alter table "schedule" alter column "title" set not null;`);
    this.addSql(`alter table "schedule" alter column "start_date" type timestamptz using ("start_date"::timestamptz);`);
    this.addSql(`alter table "schedule" alter column "start_date" set not null;`);
    this.addSql(`alter table "schedule" alter column "end_date" type timestamptz using ("end_date"::timestamptz);`);
    this.addSql(`alter table "schedule" alter column "end_date" set not null;`);
    this.addSql(`alter table "schedule" alter column "max_users" type int using ("max_users"::int);`);
    this.addSql(`alter table "schedule" alter column "max_users" set not null;`);
    this.addSql(`alter table "schedule" alter column "company_id" drop default;`);
    this.addSql(`alter table "schedule" alter column "company_id" type uuid using ("company_id"::text::uuid);`);
    this.addSql(`alter table "schedule" alter column "company_id" set not null;`);
    this.addSql(`alter table "schedule" alter column "type" type varchar(255) using ("type"::varchar(255));`);
    this.addSql(`alter table "schedule" alter column "type" set not null;`);
    this.addSql(`alter table "schedule" alter column "state" type varchar(255) using ("state"::varchar(255));`);
    this.addSql(`alter table "schedule" alter column "state" set not null;`);
    this.addSql(`alter table "schedule" alter column "admin_id" drop default;`);
    this.addSql(`alter table "schedule" alter column "admin_id" type uuid using ("admin_id"::text::uuid);`);
    this.addSql(`alter table "schedule" alter column "admin_id" set not null;`);
    this.addSql(`alter table "schedule" alter column "notified_quota_thresholds" type jsonb using ("notified_quota_thresholds"::jsonb);`);
    this.addSql(`alter table "schedule" alter column "notified_quota_thresholds" set not null;`);

    this.addSql(`alter table "schedule_wait_list_users" alter column "schedule_id" drop default;`);
    this.addSql(`alter table "schedule_wait_list_users" alter column "schedule_id" type uuid using ("schedule_id"::text::uuid);`);
    this.addSql(`alter table "schedule_wait_list_users" alter column "schedule_id" set not null;`);
    this.addSql(`alter table "schedule_wait_list_users" alter column "user_id" drop default;`);
    this.addSql(`alter table "schedule_wait_list_users" alter column "user_id" type uuid using ("user_id"::text::uuid);`);
    this.addSql(`alter table "schedule_wait_list_users" alter column "user_id" set not null;`);

    this.addSql(`alter table "refresh_token" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "refresh_token" alter column "created_at" set not null;`);
    this.addSql(`alter table "refresh_token" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "refresh_token" alter column "updated_at" set not null;`);
    this.addSql(`alter table "refresh_token" alter column "user_id" drop default;`);
    this.addSql(`alter table "refresh_token" alter column "user_id" type uuid using ("user_id"::text::uuid);`);
    this.addSql(`alter table "refresh_token" alter column "user_id" set not null;`);
    this.addSql(`alter table "refresh_token" alter column "token" type text using ("token"::text);`);
    this.addSql(`alter table "refresh_token" alter column "token" set not null;`);
    this.addSql(`alter table "refresh_token" alter column "expires_at" type timestamptz using ("expires_at"::timestamptz);`);
    this.addSql(`alter table "refresh_token" alter column "expires_at" set not null;`);

    this.addSql(`alter table "push_token" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "push_token" alter column "created_at" set not null;`);
    this.addSql(`alter table "push_token" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "push_token" alter column "updated_at" set not null;`);
    this.addSql(`alter table "push_token" alter column "token" type varchar(255) using ("token"::varchar(255));`);
    this.addSql(`alter table "push_token" alter column "token" set not null;`);
    this.addSql(`alter table "push_token" alter column "user_id" drop default;`);
    this.addSql(`alter table "push_token" alter column "user_id" type uuid using ("user_id"::text::uuid);`);
    this.addSql(`alter table "push_token" alter column "user_id" set not null;`);

    this.addSql(`alter table "poll" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "poll" alter column "created_at" set not null;`);
    this.addSql(`alter table "poll" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "poll" alter column "updated_at" set not null;`);
    this.addSql(`alter table "poll" alter column "end_date" type timestamptz using ("end_date"::timestamptz);`);
    this.addSql(`alter table "poll" alter column "end_date" set not null;`);
    this.addSql(`alter table "poll" alter column "title" type varchar(255) using ("title"::varchar(255));`);
    this.addSql(`alter table "poll" alter column "title" set not null;`);
    this.addSql(`alter table "poll" alter column "options" type text[] using ("options"::text[]);`);
    this.addSql(`alter table "poll" alter column "options" set not null;`);
    this.addSql(`alter table "poll" alter column "admin_id" drop default;`);
    this.addSql(`alter table "poll" alter column "admin_id" type uuid using ("admin_id"::text::uuid);`);
    this.addSql(`alter table "poll" alter column "admin_id" set not null;`);
    this.addSql(`alter table "poll" alter column "company_id" drop default;`);
    this.addSql(`alter table "poll" alter column "company_id" type uuid using ("company_id"::text::uuid);`);
    this.addSql(`alter table "poll" alter column "company_id" set not null;`);

    this.addSql(`alter table "poll_vote" alter column "option_selected" type int using ("option_selected"::int);`);
    this.addSql(`alter table "poll_vote" alter column "option_selected" set not null;`);

    this.addSql(`alter table "notification" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "notification" alter column "created_at" set not null;`);
    this.addSql(`alter table "notification" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "notification" alter column "updated_at" set not null;`);
    this.addSql(`alter table "notification" alter column "type" type text using ("type"::text);`);
    this.addSql(`alter table "notification" alter column "type" set not null;`);
    this.addSql(`alter table "notification" alter column "message" type varchar(255) using ("message"::varchar(255));`);
    this.addSql(`alter table "notification" alter column "message" set not null;`);
    this.addSql(`alter table "notification" alter column "user_id" drop default;`);
    this.addSql(`alter table "notification" alter column "user_id" type uuid using ("user_id"::text::uuid);`);
    this.addSql(`alter table "notification" alter column "user_id" set not null;`);
    this.addSql(`alter table "notification" alter column "title" type varchar(255) using ("title"::varchar(255));`);
    this.addSql(`alter table "notification" alter column "title" set not null;`);
    this.addSql(`alter table "notification" alter column "read" type boolean using ("read"::boolean);`);
    this.addSql(`alter table "notification" alter column "read" set not null;`);

    this.addSql(`alter table "message" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "message" alter column "created_at" set not null;`);
    this.addSql(`alter table "message" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "message" alter column "updated_at" set not null;`);
    this.addSql(`alter table "message" alter column "text" type varchar(255) using ("text"::varchar(255));`);
    this.addSql(`alter table "message" alter column "text" set not null;`);
    this.addSql(`alter table "message" alter column "is_fixed" type boolean using ("is_fixed"::boolean);`);
    this.addSql(`alter table "message" alter column "is_fixed" set not null;`);
    this.addSql(`alter table "message" alter column "is_forum_message" type boolean using ("is_forum_message"::boolean);`);
    this.addSql(`alter table "message" alter column "is_forum_message" set not null;`);
    this.addSql(`alter table "message" alter column "company_id" drop default;`);
    this.addSql(`alter table "message" alter column "company_id" type uuid using ("company_id"::text::uuid);`);
    this.addSql(`alter table "message" alter column "company_id" set not null;`);

    this.addSql(`alter table "payment_method" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "payment_method" alter column "created_at" set not null;`);
    this.addSql(`alter table "payment_method" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "payment_method" alter column "updated_at" set not null;`);
    this.addSql(`alter table "payment_method" alter column "type" type text using ("type"::text);`);
    this.addSql(`alter table "payment_method" alter column "type" set not null;`);
    this.addSql(`alter table "payment_method" alter column "status" type text using ("status"::text);`);
    this.addSql(`alter table "payment_method" alter column "status" set not null;`);
    this.addSql(`alter table "payment_method" alter column "is_default" type boolean using ("is_default"::boolean);`);
    this.addSql(`alter table "payment_method" alter column "is_default" set not null;`);

    this.addSql(`alter table "subscription" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "subscription" alter column "created_at" set not null;`);
    this.addSql(`alter table "subscription" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "subscription" alter column "updated_at" set not null;`);
    this.addSql(`alter table "subscription" alter column "user_id" drop default;`);
    this.addSql(`alter table "subscription" alter column "user_id" type uuid using ("user_id"::text::uuid);`);
    this.addSql(`alter table "subscription" alter column "user_id" set not null;`);
    this.addSql(`alter table "subscription" alter column "plan_id" drop default;`);
    this.addSql(`alter table "subscription" alter column "plan_id" type uuid using ("plan_id"::text::uuid);`);
    this.addSql(`alter table "subscription" alter column "plan_id" set not null;`);
    this.addSql(`alter table "subscription" alter column "status" type text using ("status"::text);`);
    this.addSql(`alter table "subscription" alter column "status" set not null;`);
    this.addSql(`alter table "subscription" alter column "failed_payment_attempts" type smallint using ("failed_payment_attempts"::smallint);`);
    this.addSql(`alter table "subscription" alter column "failed_payment_attempts" set not null;`);

    this.addSql(`alter table "invoice" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "invoice" alter column "created_at" set not null;`);
    this.addSql(`alter table "invoice" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "invoice" alter column "updated_at" set not null;`);
    this.addSql(`alter table "invoice" alter column "user_id" drop default;`);
    this.addSql(`alter table "invoice" alter column "user_id" type uuid using ("user_id"::text::uuid);`);
    this.addSql(`alter table "invoice" alter column "user_id" set not null;`);
    this.addSql(`alter table "invoice" alter column "status" type text using ("status"::text);`);
    this.addSql(`alter table "invoice" alter column "status" set not null;`);
    this.addSql(`alter table "invoice" alter column "subtotal" type bigint using ("subtotal"::bigint);`);
    this.addSql(`alter table "invoice" alter column "subtotal" set not null;`);
    this.addSql(`alter table "invoice" alter column "tax" type bigint using ("tax"::bigint);`);
    this.addSql(`alter table "invoice" alter column "tax" set not null;`);
    this.addSql(`alter table "invoice" alter column "total" type bigint using ("total"::bigint);`);
    this.addSql(`alter table "invoice" alter column "total" set not null;`);
    this.addSql(`alter table "invoice" alter column "amount_paid" type bigint using ("amount_paid"::bigint);`);
    this.addSql(`alter table "invoice" alter column "amount_paid" set not null;`);
    this.addSql(`alter table "invoice" alter column "amount_remaining" type bigint using ("amount_remaining"::bigint);`);
    this.addSql(`alter table "invoice" alter column "amount_remaining" set not null;`);
    this.addSql(`alter table "invoice" alter column "currency" type varchar(10) using ("currency"::varchar(10));`);
    this.addSql(`alter table "invoice" alter column "currency" set not null;`);

    this.addSql(`alter table "transaction" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "transaction" alter column "created_at" set not null;`);
    this.addSql(`alter table "transaction" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "transaction" alter column "updated_at" set not null;`);
    this.addSql(`alter table "transaction" alter column "user_id" drop default;`);
    this.addSql(`alter table "transaction" alter column "user_id" type uuid using ("user_id"::text::uuid);`);
    this.addSql(`alter table "transaction" alter column "user_id" set not null;`);
    this.addSql(`alter table "transaction" alter column "type" type text using ("type"::text);`);
    this.addSql(`alter table "transaction" alter column "type" set not null;`);
    this.addSql(`alter table "transaction" alter column "status" type text using ("status"::text);`);
    this.addSql(`alter table "transaction" alter column "status" set not null;`);
    this.addSql(`alter table "transaction" alter column "amount" type bigint using ("amount"::bigint);`);
    this.addSql(`alter table "transaction" alter column "amount" set not null;`);
    this.addSql(`alter table "transaction" alter column "amount_refunded" type bigint using ("amount_refunded"::bigint);`);
    this.addSql(`alter table "transaction" alter column "amount_refunded" set not null;`);
    this.addSql(`alter table "transaction" alter column "currency" type varchar(10) using ("currency"::varchar(10));`);
    this.addSql(`alter table "transaction" alter column "currency" set not null;`);

    this.addSql(`alter table "user_role" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "user_role" alter column "created_at" set not null;`);
    this.addSql(`alter table "user_role" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "user_role" alter column "updated_at" set not null;`);
    this.addSql(`alter table "user_role" alter column "user_id" drop default;`);
    this.addSql(`alter table "user_role" alter column "user_id" type uuid using ("user_id"::text::uuid);`);
    this.addSql(`alter table "user_role" alter column "user_id" set not null;`);
    this.addSql(`alter table "user_role" alter column "company_id" drop default;`);
    this.addSql(`alter table "user_role" alter column "company_id" type uuid using ("company_id"::text::uuid);`);
    this.addSql(`alter table "user_role" alter column "company_id" set not null;`);
    this.addSql(`alter table "user_role" alter column "role" type text using ("role"::text);`);
    this.addSql(`alter table "user_role" alter column "role" set not null;`);

    this.addSql(`alter table "user_weight" alter column "created_at" type timestamptz using ("created_at"::timestamptz);`);
    this.addSql(`alter table "user_weight" alter column "created_at" set not null;`);
    this.addSql(`alter table "user_weight" alter column "updated_at" type timestamptz using ("updated_at"::timestamptz);`);
    this.addSql(`alter table "user_weight" alter column "updated_at" set not null;`);
    this.addSql(`alter table "user_weight" alter column "weight" type real using ("weight"::real);`);
    this.addSql(`alter table "user_weight" alter column "weight" set not null;`);
    this.addSql(`alter table "user_weight" alter column "date" type varchar(255) using ("date"::varchar(255));`);
    this.addSql(`alter table "user_weight" alter column "date" set not null;`);
    this.addSql(`alter table "user_weight" alter column "company_id" drop default;`);
    this.addSql(`alter table "user_weight" alter column "company_id" type uuid using ("company_id"::text::uuid);`);
    this.addSql(`alter table "user_weight" alter column "company_id" set not null;`);
  }

  override async down(): Promise<void> {
    this.addSql(`create table "card" ("id" uuid not null, "created_at" timestamptz(6) null, "updated_at" timestamptz(6) null, "stripe_payment_method_id" varchar(255) null, "user_id" uuid null, "card_brand" varchar(255) null, "card_last4" varchar(255) null, "card_exp_month" int4 null, "card_exp_year" int4 null, "status" text check ("status" in ('active', 'inactive', 'expired')) null default 'active', "is_default" bool null default false, constraint "card_pkey" primary key ("id"));`);

    this.addSql(`create table "member_ship" ("id" uuid not null, "created_at" timestamptz(6) null, "updated_at" timestamptz(6) null, "user_id" uuid null, "company_id" uuid null, "role" text check ("role" in ('standard', 'boss', 'premium', 'coach')) null, constraint "member_ship_pkey" primary key ("id"));`);
    this.addSql(`create index "member_ship_created_at_index" on "member_ship" ("created_at");`);
    this.addSql(`alter table "member_ship" add constraint "member_ship_user_id_company_id_unique" unique ("user_id", "company_id");`);

    this.addSql(`create table "user_promotions" ("user_id" uuid not null, "promotion_id" uuid not null, constraint "user_promotions_pkey" primary key ("user_id", "promotion_id"));`);

    this.addSql(`create table "webhook_event_log" ("id" uuid not null, "created_at" timestamptz(6) null, "updated_at" timestamptz(6) null, "stripe_event_id" varchar(100) null, "event_type" varchar(100) null, "status" text check ("status" in ('pending', 'processed', 'failed', 'ignored')) null default 'pending', "payload" jsonb null, "error_message" text null, "retry_count" int2 null default 0, "processed_at" timestamptz(6) null, "last_attempt_at" timestamptz(6) null, constraint "webhook_event_log_pkey" primary key ("id"));`);
    this.addSql(`create index "webhook_event_log_stripe_event_id_index" on "webhook_event_log" ("stripe_event_id");`);

    this.addSql(`alter table "user_promotions" add constraint "user_promotions_promotion_id_foreign" foreign key ("promotion_id") references "promotion" ("id") on update cascade on delete cascade;`);
    this.addSql(`alter table "user_promotions" add constraint "user_promotions_user_id_foreign" foreign key ("user_id") references "user" ("id") on update cascade on delete cascade;`);

    this.addSql(`alter table "article" alter column "title" type varchar(255) using ("title"::varchar(255));`);
    this.addSql(`alter table "article" alter column "title" drop not null;`);
    this.addSql(`alter table "article" alter column "published_at" type varchar(255) using ("published_at"::varchar(255));`);
    this.addSql(`alter table "article" alter column "published_at" drop not null;`);
    this.addSql(`alter table "article" alter column "description" type varchar(255) using ("description"::varchar(255));`);
    this.addSql(`alter table "article" alter column "description" drop not null;`);
    this.addSql(`alter table "article" alter column "link" type varchar(255) using ("link"::varchar(255));`);
    this.addSql(`alter table "article" alter column "link" drop not null;`);
    this.addSql(`alter table "article" alter column "image" type varchar(255) using ("image"::varchar(255));`);
    this.addSql(`alter table "article" alter column "image" drop not null;`);

    this.addSql(`alter table "company" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "company" alter column "created_at" drop not null;`);
    this.addSql(`alter table "company" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "company" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "company" alter column "name" type varchar(100) using ("name"::varchar(100));`);
    this.addSql(`alter table "company" alter column "name" drop not null;`);
    this.addSql(`alter table "company" alter column "code" type varchar(255) using ("code"::varchar(255));`);
    this.addSql(`alter table "company" alter column "code" drop not null;`);
    this.addSql(`alter table "company" alter column "phone_number" type varchar(255) using ("phone_number"::varchar(255));`);
    this.addSql(`alter table "company" alter column "phone_number" drop not null;`);
    this.addSql(`alter table "company" alter column "email" type varchar(255) using ("email"::varchar(255));`);
    this.addSql(`alter table "company" alter column "email" drop not null;`);
    this.addSql(`alter table "company" alter column "address" type varchar(255) using ("address"::varchar(255));`);
    this.addSql(`alter table "company" alter column "address" drop not null;`);
    this.addSql(`alter table "company" alter column "is_validated" type bool using ("is_validated"::bool);`);
    this.addSql(`alter table "company" alter column "is_validated" drop not null;`);

    this.addSql(`alter table "company_config" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "company_config" alter column "created_at" drop not null;`);
    this.addSql(`alter table "company_config" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "company_config" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "company_config" alter column "polls_enabled" type bool using ("polls_enabled"::bool);`);
    this.addSql(`alter table "company_config" alter column "polls_enabled" drop not null;`);
    this.addSql(`alter table "company_config" alter column "products_enabled" type bool using ("products_enabled"::bool);`);
    this.addSql(`alter table "company_config" alter column "products_enabled" drop not null;`);
    this.addSql(`alter table "company_config" alter column "chat_enabled" type bool using ("chat_enabled"::bool);`);
    this.addSql(`alter table "company_config" alter column "chat_enabled" drop not null;`);
    this.addSql(`alter table "company_config" alter column "training_enabled" type bool using ("training_enabled"::bool);`);
    this.addSql(`alter table "company_config" alter column "training_enabled" drop not null;`);
    this.addSql(`alter table "company_config" alter column "auto_accept_users" type bool using ("auto_accept_users"::bool);`);
    this.addSql(`alter table "company_config" alter column "auto_accept_users" drop not null;`);

    this.addSql(`alter table "invoice" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "invoice" alter column "created_at" drop not null;`);
    this.addSql(`alter table "invoice" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "invoice" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "invoice" alter column "user_id" drop default;`);
    this.addSql(`alter table "invoice" alter column "user_id" type uuid using ("user_id"::text::uuid);`);
    this.addSql(`alter table "invoice" alter column "user_id" drop not null;`);
    this.addSql(`alter table "invoice" alter column "status" type text using ("status"::text);`);
    this.addSql(`alter table "invoice" alter column "status" drop not null;`);
    this.addSql(`alter table "invoice" alter column "subtotal" type int8 using ("subtotal"::int8);`);
    this.addSql(`alter table "invoice" alter column "subtotal" drop not null;`);
    this.addSql(`alter table "invoice" alter column "tax" type int8 using ("tax"::int8);`);
    this.addSql(`alter table "invoice" alter column "tax" drop not null;`);
    this.addSql(`alter table "invoice" alter column "total" type int8 using ("total"::int8);`);
    this.addSql(`alter table "invoice" alter column "total" drop not null;`);
    this.addSql(`alter table "invoice" alter column "amount_paid" type int8 using ("amount_paid"::int8);`);
    this.addSql(`alter table "invoice" alter column "amount_paid" drop not null;`);
    this.addSql(`alter table "invoice" alter column "amount_remaining" type int8 using ("amount_remaining"::int8);`);
    this.addSql(`alter table "invoice" alter column "amount_remaining" drop not null;`);
    this.addSql(`alter table "invoice" alter column "currency" type varchar(10) using ("currency"::varchar(10));`);
    this.addSql(`alter table "invoice" alter column "currency" drop not null;`);

    this.addSql(`alter table "message" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "message" alter column "created_at" drop not null;`);
    this.addSql(`alter table "message" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "message" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "message" alter column "text" type varchar(255) using ("text"::varchar(255));`);
    this.addSql(`alter table "message" alter column "text" drop not null;`);
    this.addSql(`alter table "message" alter column "is_fixed" type bool using ("is_fixed"::bool);`);
    this.addSql(`alter table "message" alter column "is_fixed" drop not null;`);
    this.addSql(`alter table "message" alter column "is_forum_message" type bool using ("is_forum_message"::bool);`);
    this.addSql(`alter table "message" alter column "is_forum_message" drop not null;`);
    this.addSql(`alter table "message" alter column "company_id" drop default;`);
    this.addSql(`alter table "message" alter column "company_id" type uuid using ("company_id"::text::uuid);`);
    this.addSql(`alter table "message" alter column "company_id" drop not null;`);

    this.addSql(`alter table "notification" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "notification" alter column "created_at" drop not null;`);
    this.addSql(`alter table "notification" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "notification" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "notification" alter column "type" type text using ("type"::text);`);
    this.addSql(`alter table "notification" alter column "type" drop not null;`);
    this.addSql(`alter table "notification" alter column "title" type varchar(255) using ("title"::varchar(255));`);
    this.addSql(`alter table "notification" alter column "title" drop not null;`);
    this.addSql(`alter table "notification" alter column "message" type varchar(255) using ("message"::varchar(255));`);
    this.addSql(`alter table "notification" alter column "message" drop not null;`);
    this.addSql(`alter table "notification" alter column "read" type bool using ("read"::bool);`);
    this.addSql(`alter table "notification" alter column "read" drop not null;`);
    this.addSql(`alter table "notification" alter column "user_id" drop default;`);
    this.addSql(`alter table "notification" alter column "user_id" type uuid using ("user_id"::text::uuid);`);
    this.addSql(`alter table "notification" alter column "user_id" drop not null;`);

    this.addSql(`alter table "payment_method" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "payment_method" alter column "created_at" drop not null;`);
    this.addSql(`alter table "payment_method" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "payment_method" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "payment_method" alter column "type" type text using ("type"::text);`);
    this.addSql(`alter table "payment_method" alter column "type" drop not null;`);
    this.addSql(`alter table "payment_method" alter column "status" type text using ("status"::text);`);
    this.addSql(`alter table "payment_method" alter column "status" drop not null;`);
    this.addSql(`alter table "payment_method" alter column "is_default" type bool using ("is_default"::bool);`);
    this.addSql(`alter table "payment_method" alter column "is_default" drop not null;`);

    this.addSql(`alter table "permission" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "permission" alter column "created_at" drop not null;`);
    this.addSql(`alter table "permission" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "permission" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "permission" alter column "name" type varchar(100) using ("name"::varchar(100));`);
    this.addSql(`alter table "permission" alter column "name" drop not null;`);
    this.addSql(`alter table "permission" alter column "module" type text using ("module"::text);`);
    this.addSql(`alter table "permission" alter column "module" drop not null;`);
    this.addSql(`alter table "permission" alter column "action" type text using ("action"::text);`);
    this.addSql(`alter table "permission" alter column "action" drop not null;`);
    this.addSql(`alter table "permission" alter column "is_active" type bool using ("is_active"::bool);`);
    this.addSql(`alter table "permission" alter column "is_active" drop not null;`);

    this.addSql(`alter table "picture_url" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "picture_url" alter column "created_at" drop not null;`);
    this.addSql(`alter table "picture_url" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "picture_url" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "picture_url" alter column "name" type varchar(255) using ("name"::varchar(255));`);
    this.addSql(`alter table "picture_url" alter column "name" drop not null;`);
    this.addSql(`alter table "picture_url" alter column "url" type text using ("url"::text);`);
    this.addSql(`alter table "picture_url" alter column "url" drop not null;`);

    this.addSql(`alter table "plan" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "plan" alter column "created_at" drop not null;`);
    this.addSql(`alter table "plan" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "plan" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "plan" alter column "name" type varchar(100) using ("name"::varchar(100));`);
    this.addSql(`alter table "plan" alter column "name" drop not null;`);
    this.addSql(`alter table "plan" alter column "amount" type int8 using ("amount"::int8);`);
    this.addSql(`alter table "plan" alter column "amount" drop not null;`);
    this.addSql(`alter table "plan" alter column "currency" type varchar(10) using ("currency"::varchar(10));`);
    this.addSql(`alter table "plan" alter column "currency" drop not null;`);
    this.addSql(`alter table "plan" alter column "interval" type text using ("interval"::text);`);
    this.addSql(`alter table "plan" alter column "interval" drop not null;`);
    this.addSql(`alter table "plan" alter column "interval_count" type int2 using ("interval_count"::int2);`);
    this.addSql(`alter table "plan" alter column "interval_count" drop not null;`);
    this.addSql(`alter table "plan" alter column "status" type text using ("status"::text);`);
    this.addSql(`alter table "plan" alter column "status" drop not null;`);
    this.addSql(`alter table "plan" alter column "is_active" type bool using ("is_active"::bool);`);
    this.addSql(`alter table "plan" alter column "is_active" drop not null;`);

    this.addSql(`alter table "plan_permission" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "plan_permission" alter column "created_at" drop not null;`);
    this.addSql(`alter table "plan_permission" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "plan_permission" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "plan_permission" alter column "plan_id" drop default;`);
    this.addSql(`alter table "plan_permission" alter column "plan_id" type uuid using ("plan_id"::text::uuid);`);
    this.addSql(`alter table "plan_permission" alter column "plan_id" drop not null;`);
    this.addSql(`alter table "plan_permission" alter column "permission_id" drop default;`);
    this.addSql(`alter table "plan_permission" alter column "permission_id" type uuid using ("permission_id"::text::uuid);`);
    this.addSql(`alter table "plan_permission" alter column "permission_id" drop not null;`);
    this.addSql(`alter table "plan_permission" alter column "is_active" type bool using ("is_active"::bool);`);
    this.addSql(`alter table "plan_permission" alter column "is_active" drop not null;`);

    this.addSql(`alter table "poll" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "poll" alter column "created_at" drop not null;`);
    this.addSql(`alter table "poll" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "poll" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "poll" alter column "end_date" type timestamptz(6) using ("end_date"::timestamptz(6));`);
    this.addSql(`alter table "poll" alter column "end_date" drop not null;`);
    this.addSql(`alter table "poll" alter column "title" type varchar(255) using ("title"::varchar(255));`);
    this.addSql(`alter table "poll" alter column "title" drop not null;`);
    this.addSql(`alter table "poll" alter column "options" type text[] using ("options"::text[]);`);
    this.addSql(`alter table "poll" alter column "options" drop not null;`);
    this.addSql(`alter table "poll" alter column "admin_id" drop default;`);
    this.addSql(`alter table "poll" alter column "admin_id" type uuid using ("admin_id"::text::uuid);`);
    this.addSql(`alter table "poll" alter column "admin_id" drop not null;`);
    this.addSql(`alter table "poll" alter column "company_id" drop default;`);
    this.addSql(`alter table "poll" alter column "company_id" type uuid using ("company_id"::text::uuid);`);
    this.addSql(`alter table "poll" alter column "company_id" drop not null;`);

    this.addSql(`alter table "poll_vote" alter column "option_selected" type int4 using ("option_selected"::int4);`);
    this.addSql(`alter table "poll_vote" alter column "option_selected" drop not null;`);

    this.addSql(`alter table "product" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "product" alter column "created_at" drop not null;`);
    this.addSql(`alter table "product" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "product" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "product" alter column "name" type varchar(255) using ("name"::varchar(255));`);
    this.addSql(`alter table "product" alter column "name" drop not null;`);
    this.addSql(`alter table "product" alter column "description" type varchar(255) using ("description"::varchar(255));`);
    this.addSql(`alter table "product" alter column "description" drop not null;`);
    this.addSql(`alter table "product" alter column "price" type float4 using ("price"::float4);`);
    this.addSql(`alter table "product" alter column "price" drop not null;`);
    this.addSql(`alter table "product" alter column "company_id" drop default;`);
    this.addSql(`alter table "product" alter column "company_id" type uuid using ("company_id"::text::uuid);`);
    this.addSql(`alter table "product" alter column "company_id" drop not null;`);

    this.addSql(`alter table "promotion" add column "start_date" timestamptz(6) null, add column "end_date" timestamptz(6) null, add column "price" int4 null;`);
    this.addSql(`alter table "promotion" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "promotion" alter column "created_at" drop not null;`);
    this.addSql(`alter table "promotion" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "promotion" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "promotion" alter column "title" type varchar(255) using ("title"::varchar(255));`);
    this.addSql(`alter table "promotion" alter column "title" drop not null;`);
    this.addSql(`alter table "promotion" alter column "description" type varchar(255) using ("description"::varchar(255));`);
    this.addSql(`alter table "promotion" alter column "description" drop not null;`);

    this.addSql(`alter table "push_token" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "push_token" alter column "created_at" drop not null;`);
    this.addSql(`alter table "push_token" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "push_token" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "push_token" alter column "token" type varchar(255) using ("token"::varchar(255));`);
    this.addSql(`alter table "push_token" alter column "token" drop not null;`);
    this.addSql(`alter table "push_token" alter column "user_id" drop default;`);
    this.addSql(`alter table "push_token" alter column "user_id" type uuid using ("user_id"::text::uuid);`);
    this.addSql(`alter table "push_token" alter column "user_id" drop not null;`);

    this.addSql(`alter table "refresh_token" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "refresh_token" alter column "created_at" drop not null;`);
    this.addSql(`alter table "refresh_token" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "refresh_token" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "refresh_token" alter column "user_id" drop default;`);
    this.addSql(`alter table "refresh_token" alter column "user_id" type uuid using ("user_id"::text::uuid);`);
    this.addSql(`alter table "refresh_token" alter column "user_id" drop not null;`);
    this.addSql(`alter table "refresh_token" alter column "token" type text using ("token"::text);`);
    this.addSql(`alter table "refresh_token" alter column "token" drop not null;`);
    this.addSql(`alter table "refresh_token" alter column "expires_at" type timestamptz(6) using ("expires_at"::timestamptz(6));`);
    this.addSql(`alter table "refresh_token" alter column "expires_at" drop not null;`);

    this.addSql(`alter table "schedule" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "schedule" alter column "created_at" drop not null;`);
    this.addSql(`alter table "schedule" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "schedule" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "schedule" alter column "title" type varchar(255) using ("title"::varchar(255));`);
    this.addSql(`alter table "schedule" alter column "title" drop not null;`);
    this.addSql(`alter table "schedule" alter column "start_date" type timestamptz(6) using ("start_date"::timestamptz(6));`);
    this.addSql(`alter table "schedule" alter column "start_date" drop not null;`);
    this.addSql(`alter table "schedule" alter column "end_date" type timestamptz(6) using ("end_date"::timestamptz(6));`);
    this.addSql(`alter table "schedule" alter column "end_date" drop not null;`);
    this.addSql(`alter table "schedule" alter column "max_users" type int4 using ("max_users"::int4);`);
    this.addSql(`alter table "schedule" alter column "max_users" drop not null;`);
    this.addSql(`alter table "schedule" alter column "company_id" drop default;`);
    this.addSql(`alter table "schedule" alter column "company_id" type uuid using ("company_id"::text::uuid);`);
    this.addSql(`alter table "schedule" alter column "company_id" drop not null;`);
    this.addSql(`alter table "schedule" alter column "type" type varchar(255) using ("type"::varchar(255));`);
    this.addSql(`alter table "schedule" alter column "type" drop not null;`);
    this.addSql(`alter table "schedule" alter column "state" type varchar(255) using ("state"::varchar(255));`);
    this.addSql(`alter table "schedule" alter column "state" drop not null;`);
    this.addSql(`alter table "schedule" alter column "admin_id" drop default;`);
    this.addSql(`alter table "schedule" alter column "admin_id" type uuid using ("admin_id"::text::uuid);`);
    this.addSql(`alter table "schedule" alter column "admin_id" drop not null;`);
    this.addSql(`alter table "schedule" alter column "notified_quota_thresholds" type jsonb using ("notified_quota_thresholds"::jsonb);`);
    this.addSql(`alter table "schedule" alter column "notified_quota_thresholds" drop not null;`);

    this.addSql(`alter table "schedule_options" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "schedule_options" alter column "created_at" drop not null;`);
    this.addSql(`alter table "schedule_options" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "schedule_options" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "schedule_options" alter column "max_active_reservations" type int4 using ("max_active_reservations"::int4);`);
    this.addSql(`alter table "schedule_options" alter column "max_active_reservations" drop not null;`);
    this.addSql(`alter table "schedule_options" alter column "booking_cutoff_minutes" type int4 using ("booking_cutoff_minutes"::int4);`);
    this.addSql(`alter table "schedule_options" alter column "booking_cutoff_minutes" drop not null;`);
    this.addSql(`alter table "schedule_options" alter column "min_bookings_required" type int4 using ("min_bookings_required"::int4);`);
    this.addSql(`alter table "schedule_options" alter column "min_bookings_required" drop not null;`);
    this.addSql(`alter table "schedule_options" alter column "quota_warning_thresholds" type jsonb using ("quota_warning_thresholds"::jsonb);`);
    this.addSql(`alter table "schedule_options" alter column "quota_warning_thresholds" drop not null;`);
    this.addSql(`alter table "schedule_options" alter column "max_advance_booking_days" type int4 using ("max_advance_booking_days"::int4);`);
    this.addSql(`alter table "schedule_options" alter column "max_advance_booking_days" drop not null;`);
    this.addSql(`alter table "schedule_options" alter column "same_day_booking_allowed" type bool using ("same_day_booking_allowed"::bool);`);
    this.addSql(`alter table "schedule_options" alter column "same_day_booking_allowed" drop not null;`);
    this.addSql(`alter table "schedule_options" alter column "full_open_hours" type int4 using ("full_open_hours"::int4);`);
    this.addSql(`alter table "schedule_options" alter column "full_open_hours" drop not null;`);

    this.addSql(`alter table "schedule_programmed" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "schedule_programmed" alter column "created_at" drop not null;`);
    this.addSql(`alter table "schedule_programmed" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "schedule_programmed" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "schedule_programmed" alter column "days_of_week" type text[] using ("days_of_week"::text[]);`);
    this.addSql(`alter table "schedule_programmed" alter column "days_of_week" drop not null;`);
    this.addSql(`alter table "schedule_programmed" alter column "start_hour" type time(0) using ("start_hour"::time(0));`);
    this.addSql(`alter table "schedule_programmed" alter column "start_hour" drop not null;`);
    this.addSql(`alter table "schedule_programmed" alter column "end_hour" type time(0) using ("end_hour"::time(0));`);
    this.addSql(`alter table "schedule_programmed" alter column "end_hour" drop not null;`);
    this.addSql(`alter table "schedule_programmed" alter column "max_users" type int4 using ("max_users"::int4);`);
    this.addSql(`alter table "schedule_programmed" alter column "max_users" drop not null;`);
    this.addSql(`alter table "schedule_programmed" alter column "title" type varchar(255) using ("title"::varchar(255));`);
    this.addSql(`alter table "schedule_programmed" alter column "title" drop not null;`);
    this.addSql(`alter table "schedule_programmed" alter column "description" type varchar(255) using ("description"::varchar(255));`);
    this.addSql(`alter table "schedule_programmed" alter column "description" drop not null;`);
    this.addSql(`alter table "schedule_programmed" alter column "type" type varchar(255) using ("type"::varchar(255));`);
    this.addSql(`alter table "schedule_programmed" alter column "type" drop not null;`);
    this.addSql(`alter table "schedule_programmed" alter column "company_id" drop default;`);
    this.addSql(`alter table "schedule_programmed" alter column "company_id" type uuid using ("company_id"::text::uuid);`);
    this.addSql(`alter table "schedule_programmed" alter column "company_id" drop not null;`);

    this.addSql(`alter table "schedule_wait_list_users" alter column "schedule_id" drop default;`);
    this.addSql(`alter table "schedule_wait_list_users" alter column "schedule_id" type uuid using ("schedule_id"::text::uuid);`);
    this.addSql(`alter table "schedule_wait_list_users" alter column "schedule_id" drop not null;`);
    this.addSql(`alter table "schedule_wait_list_users" alter column "user_id" drop default;`);
    this.addSql(`alter table "schedule_wait_list_users" alter column "user_id" type uuid using ("user_id"::text::uuid);`);
    this.addSql(`alter table "schedule_wait_list_users" alter column "user_id" drop not null;`);

    this.addSql(`alter table "subscription" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "subscription" alter column "created_at" drop not null;`);
    this.addSql(`alter table "subscription" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "subscription" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "subscription" alter column "user_id" drop default;`);
    this.addSql(`alter table "subscription" alter column "user_id" type uuid using ("user_id"::text::uuid);`);
    this.addSql(`alter table "subscription" alter column "user_id" drop not null;`);
    this.addSql(`alter table "subscription" alter column "plan_id" drop default;`);
    this.addSql(`alter table "subscription" alter column "plan_id" type uuid using ("plan_id"::text::uuid);`);
    this.addSql(`alter table "subscription" alter column "plan_id" drop not null;`);
    this.addSql(`alter table "subscription" alter column "status" type text using ("status"::text);`);
    this.addSql(`alter table "subscription" alter column "status" drop not null;`);
    this.addSql(`alter table "subscription" alter column "failed_payment_attempts" type int2 using ("failed_payment_attempts"::int2);`);
    this.addSql(`alter table "subscription" alter column "failed_payment_attempts" drop not null;`);

    this.addSql(`alter table "training_task" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "training_task" alter column "created_at" drop not null;`);
    this.addSql(`alter table "training_task" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "training_task" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "training_task" alter column "content" type varchar(255) using ("content"::varchar(255));`);
    this.addSql(`alter table "training_task" alter column "content" drop not null;`);
    this.addSql(`alter table "training_task" alter column "repeat" type bool using ("repeat"::bool);`);
    this.addSql(`alter table "training_task" alter column "repeat" drop not null;`);
    this.addSql(`alter table "training_task" alter column "company_id" drop default;`);
    this.addSql(`alter table "training_task" alter column "company_id" type uuid using ("company_id"::text::uuid);`);
    this.addSql(`alter table "training_task" alter column "company_id" drop not null;`);

    this.addSql(`alter table "transaction" add column "stripe_charge_id" varchar(100) null;`);
    this.addSql(`alter table "transaction" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "transaction" alter column "created_at" drop not null;`);
    this.addSql(`alter table "transaction" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "transaction" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "transaction" alter column "user_id" drop default;`);
    this.addSql(`alter table "transaction" alter column "user_id" type uuid using ("user_id"::text::uuid);`);
    this.addSql(`alter table "transaction" alter column "user_id" drop not null;`);
    this.addSql(`alter table "transaction" alter column "type" type text using ("type"::text);`);
    this.addSql(`alter table "transaction" alter column "type" drop not null;`);
    this.addSql(`alter table "transaction" alter column "status" type text using ("status"::text);`);
    this.addSql(`alter table "transaction" alter column "status" drop not null;`);
    this.addSql(`alter table "transaction" alter column "amount" type int8 using ("amount"::int8);`);
    this.addSql(`alter table "transaction" alter column "amount" drop not null;`);
    this.addSql(`alter table "transaction" alter column "amount_refunded" type int8 using ("amount_refunded"::int8);`);
    this.addSql(`alter table "transaction" alter column "amount_refunded" drop not null;`);
    this.addSql(`alter table "transaction" alter column "currency" type varchar(10) using ("currency"::varchar(10));`);
    this.addSql(`alter table "transaction" alter column "currency" drop not null;`);

    this.addSql(`alter table "user" add column "customer" varchar(255) null;`);
    this.addSql(`alter table "user" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "user" alter column "created_at" drop not null;`);
    this.addSql(`alter table "user" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "user" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "user" alter column "email" type varchar(255) using ("email"::varchar(255));`);
    this.addSql(`alter table "user" alter column "email" drop not null;`);
    this.addSql(`alter table "user" alter column "nickname" type varchar(255) using ("nickname"::varchar(255));`);
    this.addSql(`alter table "user" alter column "nickname" drop not null;`);
    this.addSql(`alter table "user" alter column "is_super_admin" type bool using ("is_super_admin"::bool);`);
    this.addSql(`alter table "user" alter column "is_super_admin" drop not null;`);
    this.addSql(`alter table "user" alter column "is_active" type bool using ("is_active"::bool);`);
    this.addSql(`alter table "user" alter column "is_active" drop not null;`);
    this.addSql(`alter table "user" alter column "is_blocked" type bool using ("is_blocked"::bool);`);
    this.addSql(`alter table "user" alter column "is_blocked" drop not null;`);
    this.addSql(`alter table "user" alter column "is_verified" type bool using ("is_verified"::bool);`);
    this.addSql(`alter table "user" alter column "is_verified" drop not null;`);
    this.addSql(`alter table "user" alter column "is_admin_verified" type bool using ("is_admin_verified"::bool);`);
    this.addSql(`alter table "user" alter column "is_admin_verified" drop not null;`);

    this.addSql(`alter table "user_role" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "user_role" alter column "created_at" drop not null;`);
    this.addSql(`alter table "user_role" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "user_role" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "user_role" alter column "user_id" drop default;`);
    this.addSql(`alter table "user_role" alter column "user_id" type uuid using ("user_id"::text::uuid);`);
    this.addSql(`alter table "user_role" alter column "user_id" drop not null;`);
    this.addSql(`alter table "user_role" alter column "company_id" drop default;`);
    this.addSql(`alter table "user_role" alter column "company_id" type uuid using ("company_id"::text::uuid);`);
    this.addSql(`alter table "user_role" alter column "company_id" drop not null;`);
    this.addSql(`alter table "user_role" alter column "role" type text using ("role"::text);`);
    this.addSql(`alter table "user_role" alter column "role" drop not null;`);

    this.addSql(`alter table "user_weight" alter column "created_at" type timestamptz(6) using ("created_at"::timestamptz(6));`);
    this.addSql(`alter table "user_weight" alter column "created_at" drop not null;`);
    this.addSql(`alter table "user_weight" alter column "updated_at" type timestamptz(6) using ("updated_at"::timestamptz(6));`);
    this.addSql(`alter table "user_weight" alter column "updated_at" drop not null;`);
    this.addSql(`alter table "user_weight" alter column "weight" type float4 using ("weight"::float4);`);
    this.addSql(`alter table "user_weight" alter column "weight" drop not null;`);
    this.addSql(`alter table "user_weight" alter column "date" type varchar(255) using ("date"::varchar(255));`);
    this.addSql(`alter table "user_weight" alter column "date" drop not null;`);
    this.addSql(`alter table "user_weight" alter column "company_id" drop default;`);
    this.addSql(`alter table "user_weight" alter column "company_id" type uuid using ("company_id"::text::uuid);`);
    this.addSql(`alter table "user_weight" alter column "company_id" drop not null;`);
  }

}
