name: _ Internal Danger
on:
  workflow_call:

jobs:
  danger-run:
    name: Pull Request Assistant
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-node@1d71da2ad040751d6f0227237077977a499c7161
        with:
          cache: 'npm'
      - run: npm ci
      - run: npx danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
