name: _ Internal Docs
on:
  workflow_call:

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-node@1d71da2ad040751d6f0227237077977a499c7161
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run docs
      - name: Deploy
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847
        with:
          github_token: ${{ github.token }}
          publish_dir: ./docs/api