name: _ Internal Security
on:
  workflow_call:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-node@1d71da2ad040751d6f0227237077977a499c7161
        with:
          node-version: '22' # Usamos la última para auditorías más frescas
      - run: npm ci
      - name: Audit High/Critical
        run: npm audit --audit-level=high # Pro-tip: Solo rompe el build si el riesgo es real
      - name: Outdated
        run: npm outdated || true # Pro-tip: No falla el build por paquetes viejos, solo informa