name: _ Internal Tests
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN: { required: true }

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-node@1d71da2ad040751d6f0227237077977a499c7161
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Run Tests
        run: npm run test:ci
        env:
          NODE_ENV: test

      - name: Upload to Codecov
        if: matrix.node-version == '20.x' # Solo subimos el reporte de una versión para no duplicar
        uses: codecov/codecov-action@7f90370603701620c3a647900b80f12a2083d800
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true
          verbose: true

          # --- ARTEFACTO PARA SONARCLOUD ---
      - name: Upload Coverage Artifact
        if: matrix.node-version == '20.x'
        uses: actions/upload-artifact@65c84d6411d33189d9c6665c36f338b251a37c4e
        with:
          name: coverage-artifact
          path: coverage/
          retention-days: 1