name: _ Internal Tests
on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-node@39225597fd66c219463660335c02633935665959
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Run Tests
        run: npm run test:ci
        env:
          NODE_ENV: test

      - name: Upload to Codecov
        if: matrix.node-version == '20.x' # Solo subimos el reporte de una versión para no duplicar
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true
          verbose: true

          # --- ARTEFACTO PARA SONARCLOUD ---
      - name: Upload Coverage Artifact
        if: matrix.node-version == '20.x'
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882
        with:
          name: coverage-artifact
          path: coverage/
          retention-days: 1